/*
 * ARPScannerDriver.h
 *
 *  Created on: Jan 13, 2017
 *      Author: Christian Everett
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef BLUETOOTHDRIVER_H_
#define BLUETOOTHDRIVER_H_

/* Header for class Test */

#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:
 * Method:
 * Signature:
 */
JNIEXPORT void JNICALL Java_com_pi_devices_asynchronousdevices_BluetoothAdapter_setupBluetooth(JNIEnv *, jobject);
JNIEXPORT jobjectArray JNICALL Java_com_pi_devices_asynchronousdevices_BluetoothAdapter_scanForBluetoothDevices(JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_pi_devices_asynchronousdevices_BluetoothAdapter_ping(JNIEnv *, jobject, jstring);
JNIEXPORT void JNICALL Java_com_pi_devices_asynchronousdevices_BluetoothAdapter_closeBluetooth(JNIEnv *, jobject);

#ifdef __cplusplus
}

#endif

#endif /* BLUETOOTHDRIVER_H_ */
