
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_TempDriver
#define _Included_TempDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     
 * Method:    
 * Signature: 
 */
JNIEXPORT jdouble JNICALL Java_com_thermostat_Thermostat_readSensor(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
